### PR TITLE
Return non-zero exit code when verify command fails

### LINKED ISSUE #224: If verify fails, `cargo msrv` should have a non-zero return code
When checking MSRV in CI, it is helpful when a command that fails has a non-zero return code. If it doesn't, we end up having to parse stdout/stderr for strings like Failure. For example, I seem to have to do this in my CI for a project:
```
cargo msrv --verify --output-format json | grep "\"success\":true"
```

I poked around the source code to try to see how to best fix this, but it was hard to follow, so I'm not sure how best to propagate this failure to an eventual `return Err(something);` in `main`. Or `std::process:exit`

### PR DESCRIPTION
**Pull request by foresterre**
closes #224

### CODE REVIEW

File: src/subcommands/verify_msrv.rs [hunk 1]
```diff
@@ -29,15 +30,22 @@ pub fn run_verify_msrv_action<R: Output>(
...
     let cmd = config.check_command_string();
     reporter.mode(ModeIntent::VerifyMSRV);
     let status = check_toolchain(version, config, reporter)?;
     report_verify_completion(reporter, &status, &cmd);
 
-    Ok(())
+    if status.is_success() {
+        Ok(())
+    } else {
+        Err(CargoMSRVError::SubCommandVerify(Error::VerifyFailed {
```
Comment (foresterre) [inline src/subcommands/verify_msrv.rs:44]: By returning an Err, cargo-msrv will return with a non-zero exit code, as per https://github.com/foresterre/cargo-msrv/blob/a27a100a59ccf0eded1e1ff6eaddfd0f4a7c387a/src/bin/cargo-msrv.rs#L26-L34

The other changes are to support the two added test cases, which should ensure we'll keep returning a non-zero exit code on failure of verify (and a zero exit code for success) in the future.
