### PR TITLE
Fix some errors not being reported on console

### LINKED ISSUE #934: No console output for `msrv verify` if `rust-version` is missing or invalid
## Version
cargo-msrv: latest `main` branch commit (currently 86997c959a8f923636281b0d80260590b0730f64)
cargo: 1.79.0

Windows 10

## Description
When running `cargo msrv verify` but the `Cargo.toml` file contains no `rust-version` entry or its value is invalid, it just exits with code 1, but nothing is printed to console.

Only when running with `--log-target stdout` the error is visible:
> ERROR cargo_msrv: Unable to find key 'package.rust-version' (or 'package.metadata.msrv') in '\<project>\Cargo.toml'

### Expected behavior
The error should be printed to console by default to make it more obvious why the command failed.

### PR DESCRIPTION
**Pull request by Marcono1234**
Fixes #934

It seems there were two issues:
- Conversion from `CargoMSRVError` to `InstanceError`
- `InstanceError` not being shown on console by default, but instead only being logged with `tracing::error!`
(and usage of `tracing::error!` might also have been problematic because the `InstanceError` might be about setup of `tracing` having failed)

It looks like this can be solved by removing `Context::output_format` (since this information is also available from `opts`), and then performing the `Context::try_from` call later and handling errors like normal execution errors.

For now I have marked this as draft and added some notes as comments below. Please let me know if I overlooked something, and what you think.

### CODE REVIEW

File: src/bin/cargo-msrv.rs [hunk 1]
```diff
@@ -18,20 +18,25 @@ use cargo_msrv::{run_app, Context, OutputFormat, TracingOptions, TracingTargetOp
...
                 ExitCode::Failure
             }
         }
         .into(),
     );
 }
 
-fn _main<I: IntoIterator<Item = OsString>, F: FnOnce() -> I + Clone>(
+/// Step 1: Parse options and set up tracing
+fn _main_1<I: IntoIterator<Item = OsString>, F: FnOnce() -> I + Clone>(
```
Comment (Marcono1234) [inline src/bin/cargo-msrv.rs:37]: I have chosen the `_main_1`, `_main_2` and `_main_3` names just for the first proof-of-concept. Please let me know if you have ideas for better names, or if I should merge some of the functions.

File: src/bin/cargo-msrv.rs [hunk 2]
```diff
@@ -68,13 +73,13 @@ fn init_and_run(ctx: &Context) -> Result<ExitCode, InstanceError> {
 
     tracing::info!("storyteller channel created");
 
-    let output_format = ctx.output_format();
+    let output_format = opts.shared_opts.user_output_opts.output_format;
```
Comment (Marcono1234) [inline src/bin/cargo-msrv.rs:76]: I hope this is fine and there is no way `output_format()` could differ from `opts.shared_opts.user_output_opts.output_format`.

File: src/bin/cargo-msrv.rs [hunk 3]
```diff
@@ -255,21 +266,16 @@ enum TracingGuard {
...
 #[derive(Debug, thiserror::Error)]
-enum InstanceError {
-    // Only for compat. with `Context::try_from`, which is not as easily converted to this Error type
-    // of the bin crate.
-    // For that reason, we do not derive `#[from] CargoMSRVError`, so we don't silently miss calls
-    // which may produce an `Err(CargoMSRVError)` where we do not want it.
-    #[error("{0}")]
-    CargoMsrv(CargoMSRVError),
-
+enum SetupError {
```
Comment (Marcono1234) [inline src/bin/cargo-msrv.rs:278]: If you want I can revert this again to `InstanceError` or any other name you think fits better.

File: src/bin/cargo-msrv.rs (hunk 2 above)
Comment (foresterre) [reply src/bin/cargo-msrv.rs:76]: We should be able to find a way to use the context.

In cargo-msrv, the context can be considered a resolved, merged and immutable set of inputs (and are split per subcommand; it's an enum). The (...)Opts are CLI arguments. 

In the future I will also add (more) environment variables and potentially support for a config file. These input sets will be merged according to some precedence. So, concretely, if at some point we have:

- `CargoMsrvOpts`
- `CargoMsrvEnvVars`
- `CargoMsrvConfigFile`

Then after resolving and merging these, the remaining inputs for the program is the `Context`.

(Thanks for the PR 😄, I'll do a full review later)

File: src/bin/cargo-msrv.rs [hunk 4]
```diff
@@ -18,20 +18,25 @@ use cargo_msrv::{run_app, Context, OutputFormat, TracingOptions, TracingTargetOp
...
-        match _main(std::env::args_os) {
+        match _main_1(std::env::args_os) {
             Ok((_guard, exit_code)) => exit_code,
             Err(err) => {
-                tracing::error!("{}", err);
+                // Don't use `tracing::error!` here because maybe an issue with `tracing` setup is what
+                // caused this error in the first place
+                // Additionally `tracing::error!` would not print to console by default, so user would not
+                // know what went wrong
+                println!("Setup error: {}", err);
```
Comment (foresterre) [inline src/bin/cargo-msrv.rs:28]: If we're going to do this (I'm not against it per se), then we should be using `eprintln!` instead of `println`.

**Comment by foresterre** [comment]
Hey, Thanks a lot for the PR!

I think I gave you the wrong pointer previously in #934, because once the context is built, it is assumed we have a RustVersion:

https://github.com/foresterre/cargo-msrv/blob/main/src/context/verify.rs#L16

Looking in more detail at this PR, I think you're on the right track. An error is produced after all (courtesy of [`Context::try_from`](https://github.com/foresterre/cargo-msrv/blob/main/src/bin/cargo-msrv.rs#L56)).

The first step which I feel is a good step in the right direction, is to change the tracing::error! to a `println`, here:

https://github.com/foresterre/cargo-msrv/pull/963/files/2bee052a328af82a191d8712edaa63a0bd5cb06e#diff-72a8660bff7d91b9c1e7985d434a773cbe58c206ff5f337bcef8fb3ee8bace75L24-R28

There is a small problem though 🥲!

This works for human output methods, e.g. running `cargo msrv verify` on a project with no rust-version gives us: 

```
     Running `cargo-msrv.exe msrv verify --path ..\codecrafters-redis-rust`
Unable to find key 'package.rust-version' (or 'package.metadata.msrv') in '..\codecrafters-redis-rust\Cargo.toml'
```


However, we don't want this kind of output if the `output-format` is, for example `json` (or: not `human`), while it currently does:

```
     Running `cargo-msrv.exe msrv verify --path ..\codecrafters-redis-rust\ --output-format json`
Unable to find key 'package.rust-version' (or 'package.metadata.msrv') in '..\codecrafters-redis-rust\Cargo.toml'
```

The problem is that I've initialized the https://github.com/foresterre/cargo-msrv/blob/main/src/bin/cargo-msrv.rs#L56 before the [reporter](https://github.com/foresterre/cargo-msrv/blob/main/src/bin/cargo-msrv.rs#L66-L73).

It makes to do so because the context also tells us, which output format ought to be used (i.e. which reporter handler to use) so it's a bit of a chicken and egg problem.

**Comment by foresterre** [comment]
One way to solve it would be to manually print `json` in the event that the output format is json. Using `opts` is perhaps not ideal over context, but we have to be pragmatic here.

The property is `opts.shared_opts.user_opts`. I believe you already accessed it too 😄.

I made a small proof of concept, similar to yours:

```
fn main() {
    let opts = parse_opts(std::env::args_os);
    let output_format = opts.shared_opts.user_output_opts.output_format;

    std::process::exit(
        match _main(opts) {
            Ok((_guard, exit_code)) => exit_code,
            Err(err) => {
                // Can't use tracing::error! here, because it may not have been initialized!
                report_init_err(err, output_format);

                ExitCode::Failure
            }
        }
        .into(),
    );
}

fn report_init_err(err: InstanceError, output_format: OutputFormat) {
    match output_format {
        OutputFormat::Human => eprintln!("{}", err),
        OutputFormat::Minimal => eprintln!("error\n{}", err),
        OutputFormat::Json => {
            eprintln!(
                "{}",
                serde_json::json!({
                    "type": "init",
                    "failure": format!("{}", err),
                })
            );
        }
        OutputFormat::None => {}
    }
}

fn parse_opts<I: IntoIterator<Item = OsString>, F: FnOnce() -> I + Clone>(
    args: F,
) -> CargoMsrvOpts {
    let matches = CargoCli::parse_args(args());
    let opts = matches.to_cargo_msrv_cli().to_opts();

    opts
}
```

And then `fn _main` can simply be:

```
fn _main(opts: CargoMsrvOpts) -> Result<(Option<TracingGuard>, ExitCode), InstanceError> {
``` 

Compared to yours I tried to keep as much intact (but as you can see it's very similar in concept), and did some manual effort to get the right output format.


P.S. If you want to rename the vague `InstanceError` to `SetupError` feel free to do so.

**Review by foresterre — CHANGES_REQUESTED** [review]
We need to address the different output formats. Please see my other comments for details.

- [ ] use `eprintln!` over `println!`
- [ ] handle all output formats
- [ ] rename _main_1 etc. to more descriptive names

**Comment by Marcono1234** [comment]
Are you sure that the `output-format` handling is really a problem with my proposed changes here? Note that the `println!` I added is only as fallback in case something goes really wrong (I assume), something which should never happen.

Because I am calling `Context::try_from` a bit later now, and expected program errors such as the "Unable to find key ..." error are properly handled and respect the `--output-format`; they don't reach the `println!`.

In my opinion calling `Context::try_from` later, as done in this pull request, is the most important fix to this, since it makes sure then that all expected program errors are handled at the same place. The switch from `tracing::error!` to `println!` is nice to have (also for correctness), but not strictly needed to fix the original issue here.

**Comment by foresterre** [comment]
Thanks for the explanation! That will do it indeed.

Then I only have the request to rename the different `_main_n` functions to more descriptive names :)

**Comment by Marcono1234** [comment]
> Then I only have the request to rename the different `_main_n` functions to more descriptive names :)

Do you have any suggestions? `_main_n` might not be that descriptive but at least it makes the order clear.
I guess `_main_3` can be named `run_program` or similar. But for `_main_1` and `_main_2` I am not sure if a more descriptive name is more helpful (also since they are doing multiple things), and just based on the names it won't be obvious in which order they run. I can't think of very good names for them at the moment.

**Comment by foresterre** [comment]
> > Then I only have the request to rename the different `_main_n` functions to more descriptive names :)
> 
> Do you have any suggestions? `_main_n` might not be that descriptive but at least it makes the order clear. I guess `_main_3` can be named `run_program` or similar. But for `_main_1` and `_main_2` I am not sure if a more descriptive name is more helpful (also since they are doing multiple things), and just based on the names it won't be obvious in which order they run. I can't think of very good names for them at the moment.

Just some ideas:

1) setup_opts_and_tracing
2) setup_reporter
3) setup_context

or

1) run_with_opts_and_tracing
2) run_with_reporter
3) run_with_context

An alternative could be to let setup_context (_main_3) return the context and call run_app from main.

**Comment by Marcono1234** [comment]
Thanks for the feedback and the suggestions! I have adjusted the code now, and force-pushed the changes. Please let me know if I should change anything else.

File: src/cli/shared_opts.rs [hunk 5]
```diff
@@ -33,11 +33,21 @@ pub struct UserOutputOpts {
         value_name = "FORMAT",
         global = true
     )]
-    pub output_format: OutputFormat,
+    output_format: OutputFormat,
 
     /// Disable user output
     #[arg(long, global = true)]
-    pub no_user_output: bool,
+    no_user_output: bool,
```
Comment (Marcono1234) [inline src/cli/shared_opts.rs:40]: Removed `pub` from them to force usage of the new `effective_output_format()` method to prevent anyone else from making the same error I did when directly using `output_format`, see https://github.com/foresterre/cargo-msrv/pull/963/files#r1708224557.

**Review by foresterre — APPROVED** [review]
Thank you!
